/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:94a0af2b-a80a-4b0e-8e5d-b3ac4391a325",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fE46ROHvh",
    "aws_user_pools_web_client_id": "1805omvairpkn7vlfutckc9m5t",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://ulc4grijpfce7etzwzhnslgywu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-oop2rv7ud5ebbhgcxfl7r6qnzm",
    "aws_user_files_s3_bucket": "amplifyreacte1f2af9eb57642468f8910cbafc8f45b94400-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
